name: CI
on: push
env:
  POETRY_VIRTUALENVS_PATH: /home/runner/.cache/pypoetry/virtualenvs/env

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11
      - name: Virtualenv
        run: |
          python -m venv $POETRY_VIRTUALENVS_PATH
          export PATH=$POETRY_VIRTUALENVS_PATH/bin:$PATH
      - name: Python path
        run: which python
      # - name: Install dependencies
      #   run: poetry install
      # - name: Install gdown
      #   run: python -m pip install gdown
      # - name: Download data
      #   run: ./github/scripts/prepare_data.sh
      #   shell: bash
      # - name: Test
      #   run: ls pretrain
